version: '3'
services:
  app:
    container_name: plant_water
    image: plant_water
    build: .
    volumes:
      - ".:/app"
    depends_on:
      - mosquitto
    environment:
    - PYTHONUNBUFFERED=1
    - MQTT_BROKER=mosquitto
    - MQTT_PORT=1883
    command: python /app/src/app.py

  mosquitto:
    container_name: mqtt
    image: "eclipse-mosquitto:latest"
    ports:
      - 1883:1883
