version: 2.1
jobs:
  build:
    machine:
      image: cimg/base:2020.01

    steps:
      - checkout

      - run:
          name: Build project
          command: make build

      - run:
          name: Run tests
          command: make test