version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Run tests
          command: pip install -r requirements.txt && make test

      - run:
          name: Build project
          command: make build

      - store_test_results:
          path: reports/

      - store_artifacts:
          path: reports/coverage.html